name: Run Main Script on Push

on:
  push:
    branches:
      - main
    paths-ignore:
      - "amstat/input/**"
      - "amstat/output/**"

jobs:
  run_script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout workplace
        uses: actions/checkout@v4
        with:
            ref: ${{ github.head_ref }}

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl

      - name: Run python script
        run: |
          python main.py

      - name: Commit and push generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: "CI automated changes"
            branch: main
